[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "/donate"
    weight = 3


# Social Media Configuration


[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ilovethensa"
    weight = 3