# Homepage Config
isSinglePage = true

# Meta Config
description = "THT's den"

# Header Configuration
avatar = "img/profile-picture.jpg"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

 # giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = true
    repo = "ilovethensa/blog"
    repoId = "R_kgDOKrbBnw"
    category = "Announcements"
    categoryId = "DIC_kwDOKrbBn84CfTbO"
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    lazyLoading = true